# Builds the Python package in ADO.
# Required for internal validations, like component governance.

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements_dev.txt
    make dist
  displayName: 'Build package'
- script: |
    python -m pip install dist/*.whl
  displayName: 'Install package'
- script: |
    pytest
  displayName: 'Test package'
- publish: dist
  artifact: Wheels
  displayName: Upload Python Artifacts
  condition: eq(variables['python.version'], '3.8')

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'
